mixed-port: 7890
allow-lan: false
mode: 'rule'
log-level: 'warning'
ipv6: false
proxies:
  - name: '🇺🇸US_691|124KB/s|R002-260618 01'
    port: 7615
    server: '47.90.206.169'
    skip-cert-verify: true
    sub_tag: 'R002-260618'
    tls: true
    type: 'http'
    udp: true
  - name: '🇺🇸US_174|1.1MB/s|R002-260618 01'
    port: 443
    server: '52.55.81.168'
    skip-cert-verify: true
    sub_tag: 'R002-260618'
    tls: true
    type: 'http'
    udp: true
  - name: '🇺🇸US_473|1.4MB/s|P002-260618 01'
    password: 'None'
    port: 443
    server: '52.55.81.168'
    skip-cert-verify: true
    sub_tag: 'P002-260618'
    tls: true
    type: 'http'
    udp: true
  - name: '🇺🇸US_566|735KB/s|R002-260618 01'
    port: 442
    server: '54.235.192.64'
    sub_tag: 'R002-260618'
    type: 'http'
    udp: true
  - name: '🇺🇸US_624|1.4MB/s 01'
    password: 'null'
    port: 443
    server: '52.55.81.168'
    skip-cert-verify: true
    tls: true
    type: 'http'
    username: 'null'
    udp: true
  - cipher: 'aes-128-gcm'
    name: '🇺🇸US_13|402KB/s|A004-260618 01'
    password: 'shadowsocks'
    port: 443
    server: '37.19.198.236'
    sub_tag: 'A004-260618'
    type: 'ss'
    udp: true
  - cipher: 'aes-128-gcm'
    name: '🇺🇸US_466|979KB/s 01'
    password: 'shadowsocks'
    port: 443
    server: '37.19.198.243'
    type: 'ss'
    udp: true
  - alterId: 0
    cipher: 'auto'
    name: '🇺🇸US_90|1.1MB/s|A004-260618 01'
    network: 'tcp'
    port: 18000
    server: '67.220.85.46'
    skip-cert-verify: false
    sub_tag: 'A004-260618'
    tls: false
    type: 'vmess'
    udp: true
    uuid: 'f8c8dc3d-0d37-46b0-8b34-a7232882fcfe'
    xudp: true
    packet-encoding: 'xudp'
    servername: '67.220.85.46'
  - cipher: 'aes-128-gcm'
    name: '🇺🇸US_412|1013KB/s|A004-260618 01'
    password: 'shadowsocks'
    port: 443
    server: '37.19.198.244'
    sub_tag: 'A004-260618'
    type: 'ss'
    udp: true
  - alpn:
      - ''
    alterId: '0'
    cipher: 'auto'
    name: '🇺🇸US_28|591KB/s|T001-260618 01'
    network: 'tcp'
    port: 22324
    server: '216.106.183.35'
    skip-cert-verify: false
    sub_tag: 'T001-260618'
    tls: false
    type: 'vmess'
    udp: true
    uuid: '04621bae-ab36-11ec-b909-0242ac120002'
    xudp: true
    packet-encoding: 'xudp'
  - cipher: 'chacha20-ietf-poly1305'
    name: '🇺🇸US_119|1.5MB/s|B007-260618 01'
    password: 'YHtesZ0qvgtg'
    port: 8388
    server: '38.180.135.156'
    sub_tag: 'B007-260618'
    type: 'ss'
    udp: true
  - name: '🇺🇸US_325|1.2MB/s|R002-260618 01'
    password: 'e4b72b531a2d10900519'
    port: 443
    server: '147.182.216.4'
    sni: '93b6d804.acsnet.co'
    sub_tag: 'R002-260618'
    tls: true
    type: 'http'
    username: 'testuser1'
    udp: true
  - alterId: '0'
    cipher: 'aes-128-gcm'
    name: '🇺🇸US_70|1.3MB/s|C002-260622 01'
    network: 'raw'
    port: 18000
    server: '67.220.85.46'
    skip-cert-verify: false
    sub_tag: 'C002-260622'
    tls: false
    type: 'vmess'
    udp: true
    uuid: 'f8c8dc3d-0d37-46b0-8b34-a7232882fcfe'
    xudp: true
    packet-encoding: 'xudp'
  - cipher: 'aes-128-gcm'
    name: '🇺🇸US_16|892KB/s 01'
    password: 'shadowsocks'
    port: 443
    server: '37.19.198.160'
    type: 'ss'
    udp: true
  - name: '🇺🇸US_471|1.0MB/s|K001-260618 01'
    password: 'e4b72b531a2d10900519'
    port: 443
    server: '147.182.216.4'
    skip-cert-verify: true
    sub_tag: 'K001-260618'
    tls: true
    type: 'http'
    username: 'testuser1'
    udp: true
  - name: '🇺🇸US-140.82.63.79-404'
    server: '140.82.63.79'
    port: 8388
    type: 'ss'
    cipher: 'chacha20-ietf-poly1305'
    password: 'ZoZtfPOyVvmKARUN'
    _poolOnly: true
  - client-fingerprint: 'chrome'
    name: '🇫🇷FR_425|1.3MB/s|A004-260618 01'
    network: 'ws'
    port: 443
    server: '216.205.52.146'
    sub_tag: 'A004-260618'
    tls: true
    type: 'vless'
    udp: true
    uuid: 'b2593749-691c-428c-9481-14979cba3446'
    ws-opts:
      headers:
        Host: 'xi.tbv.ccwu.cc'
        User-Agent: 'Mozilla/5.0 (X11; Linux i686) AppleWebKit/534.30 (KHTML, like Gecko) Slackware/Chrome/12.0.742.100 Safari/534.30'
      path: '/proxyip=us.xiabibi.cf'
    xudp: true
    packet-encoding: 'xudp'
    servername: 'xi.tbv.ccwu.cc'
  - client-fingerprint: 'chrome'
    name: '🇫🇷FR_340|1.2MB/s|A004-260618 01'
    network: 'ws'
    port: 443
    server: '104.18.26.90'
    sub_tag: 'A004-260618'
    tls: true
    type: 'vless'
    udp: true
    uuid: 'b2593749-691c-428c-9481-14979cba3446'
    ws-opts:
      headers:
        Host: 'xi.tbv.ccwu.cc'
        User-Agent: 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36'
      path: '/proxyip=us.xiabibi.cf'
    xudp: true
    packet-encoding: 'xudp'
    servername: 'xi.tbv.ccwu.cc'
  - cipher: 'chacha20-ietf-poly1305'
    name: '🇺🇸US_424|1.9MB/s 01'
    password: 'eDfN7SODQceIOmIAbtJJtK'
    port: 443
    server: '198.98.53.130'
    type: 'ss'
    udp: true
  - encryption: 'none'
    name: '🇺🇸US_821|1.2MB/s|M002-260618 01'
    network: 'ws'
    port: 8081
    server: '162.35.96.39'
    sub_tag: 'M002-260618'
    type: 'vless'
    udp: true
    uuid: '54ee5e59-55a3-4599-83ff-0c67b3f411b2'
    ws-opts:
      headers:
        Host: ''
        User-Agent: 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36'
      path: '/vless-test'
    xudp: true
    packet-encoding: 'xudp'
  - name: '🇺🇸US_748|892KB/s|A004-260618 01'
    network: 'ws'
    port: 8081
    server: '162.35.96.15'
    sub_tag: 'A004-260618'
    type: 'vless'
    udp: true
    uuid: '54ee5e59-55a3-4599-83ff-0c67b3f411b2'
    ws-opts:
      headers:
        Host: ''
        User-Agent: 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36'
      path: '/vless-test'
    xudp: true
    packet-encoding: 'xudp'
  - name: '🇺🇸US_799|1.5MB/s|A004-260618 01'
    network: 'ws'
    port: 8081
    server: '162.35.96.21'
    sub_tag: 'A004-260618'
    type: 'vless'
    udp: true
    uuid: '54ee5e59-55a3-4599-83ff-0c67b3f411b2'
    ws-opts:
      headers:
        Host: ''
        User-Agent: 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36'
      path: '/vless-test'
    xudp: true
    packet-encoding: 'xudp'
  - client-fingerprint: 'chrome'
    encryption: 'none'
    name: '🇫🇷FR_381|1.0MB/s|S004-260618 01'
    network: 'ws'
    port: 443
    server: '31.43.179.106'
    sub_tag: 'S004-260618'
    tls: true
    type: 'vless'
    udp: true
    uuid: 'b2593749-691c-428c-9481-14979cba3446'
    ws-opts:
      headers:
        Host: 'xi.tbv.ccwu.cc'
        User-Agent: 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36'
      path: '/proxyip=us.xiabibi.cf'
    xudp: true
    packet-encoding: 'xudp'
    servername: 'xi.tbv.ccwu.cc'
  - type: 'vless'
    name: '美国+CloudFlare节点-3467fe599d055525'
    server: 'teddy.automizely.com'
    port: 443
    tls: true
    uuid: 'b2593749-691c-428c-9481-14979cba3446'
    network: 'ws'
    sni: 'xi.tbv.ccwu.cc'
    ws-opts:
      path: '/proxyip=us.xiabibi.cf'
      headers:
        Host: 'xi.tbv.ccwu.cc'
    _poolOnly: true
  - client-fingerprint: 'chrome'
    name: '🇫🇷FR_359|767KB/s|A004-260618 01'
    network: 'ws'
    port: 443
    server: '66.235.200.218'
    sub_tag: 'A004-260618'
    tls: true
    type: 'vless'
    udp: true
    uuid: 'b2593749-691c-428c-9481-14979cba3446'
    ws-opts:
      headers:
        Host: 'xi.tbv.ccwu.cc'
        User-Agent: 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36'
      path: '/proxyip=us.xiabibi.cf'
    xudp: true
    packet-encoding: 'xudp'
    servername: 'xi.tbv.ccwu.cc'
  - client-fingerprint: 'chrome'
    name: '🇫🇷FR_271|1.4MB/s|S001-260618 01'
    network: 'ws'
    port: 443
    server: 'fi1.zuoai.cf'
    sub_tag: 'S001-260618'
    tls: true
    type: 'vless'
    udp: true
    uuid: 'b2593749-691c-428c-9481-14979cba3446'
    ws-opts:
      headers:
        Host: 'xi.tbv.ccwu.cc'
        User-Agent: 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36'
      path: '/proxyip=us.xiabibi.cf'
    servername: 'xi.tbv.ccwu.cc'
  - client-fingerprint: 'chrome'
    name: '🇫🇷FR_414|1.0MB/s|A004-260618 01'
    network: 'ws'
    port: 443
    server: '45.131.5.248'
    sub_tag: 'A004-260618'
    tls: true
    type: 'vless'
    udp: true
    uuid: 'b2593749-691c-428c-9481-14979cba3446'
    ws-opts:
      headers:
        Host: 'xi.tbv.ccwu.cc'
        User-Agent: 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36'
      path: '/proxyip=us.xiabibi.cf'
    xudp: true
    packet-encoding: 'xudp'
    servername: 'xi.tbv.ccwu.cc'
  - client-fingerprint: 'chrome'
    name: '🇫🇷FR_421|1.4MB/s|A004-260618 01'
    network: 'ws'
    port: 443
    server: '212.104.128.27'
    sub_tag: 'A004-260618'
    tls: true
    type: 'vless'
    udp: true
    uuid: 'b2593749-691c-428c-9481-14979cba3446'
    ws-opts:
      headers:
        Host: 'xi.tbv.ccwu.cc'
        User-Agent: 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36'
      path: '/proxyip=us.xiabibi.cf'
    xudp: true
    packet-encoding: 'xudp'
    servername: 'xi.tbv.ccwu.cc'
  - client-fingerprint: 'chrome'
    name: '🇫🇷FR_423|799KB/s|A004-260618 01'
    network: 'ws'
    port: 443
    server: '45.131.5.33'
    sub_tag: 'A004-260618'
    tls: true
    type: 'vless'
    udp: true
    uuid: 'b2593749-691c-428c-9481-14979cba3446'
    ws-opts:
      headers:
        Host: 'xi.tbv.ccwu.cc'
        User-Agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36'
      path: '/proxyip=us.xiabibi.cf'
    xudp: true
    packet-encoding: 'xudp'
    servername: 'xi.tbv.ccwu.cc'
  - client-fingerprint: 'chrome'
    name: '🇫🇷FR_351|1.4MB/s|A004-260618 01'
    network: 'ws'
    port: 443
    server: '104.16.111.193'
    sub_tag: 'A004-260618'
    tls: true
    type: 'vless'
    udp: true
    uuid: 'b2593749-691c-428c-9481-14979cba3446'
    ws-opts:
      headers:
        Host: 'xi.tbv.ccwu.cc'
        User-Agent: 'Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36'
      path: '/proxyip=us.xiabibi.cf'
    xudp: true
    packet-encoding: 'xudp'
    servername: 'xi.tbv.ccwu.cc'
  - client-fingerprint: 'chrome'
    name: '🇫🇷FR_273|569KB/s|S001-260618 01'
    network: 'ws'
    port: 443
    server: 'us2.zuoai.cf'
    sub_tag: 'S001-260618'
    tls: true
    type: 'vless'
    udp: true
    uuid: 'b2593749-691c-428c-9481-14979cba3446'
    ws-opts:
      headers:
        Host: 'xi.tbv.ccwu.cc'
        User-Agent: 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36'
      path: '/proxyip=us.xiabibi.cf'
    servername: 'xi.tbv.ccwu.cc'
  - client-fingerprint: 'chrome'
    name: '🇫🇷FR_361|567KB/s|A004-260618 01'
    network: 'ws'
    port: 443
    server: '66.235.200.171'
    sub_tag: 'A004-260618'
    tls: true
    type: 'vless'
    udp: true
    uuid: 'b2593749-691c-428c-9481-14979cba3446'
    ws-opts:
      headers:
        Host: 'xi.tbv.ccwu.cc'
        User-Agent: 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36'
      path: '/proxyip=us.xiabibi.cf'
    xudp: true
    packet-encoding: 'xudp'
    servername: 'xi.tbv.ccwu.cc'
  - client-fingerprint: 'chrome'
    name: '🇫🇷FR_420|1.2MB/s|A004-260618 01'
    network: 'ws'
    port: 443
    server: '45.131.5.80'
    sub_tag: 'A004-260618'
    tls: true
    type: 'vless'
    udp: true
    uuid: 'b2593749-691c-428c-9481-14979cba3446'
    ws-opts:
      headers:
        Host: 'xi.tbv.ccwu.cc'
        User-Agent: 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36'
      path: '/proxyip=us.xiabibi.cf'
    xudp: true
    packet-encoding: 'xudp'
    servername: 'xi.tbv.ccwu.cc'
  - client-fingerprint: 'chrome'
    name: '🇫🇷FR_358|1.6MB/s|A004-260618 01'
    network: 'ws'
    port: 443
    server: '66.235.200.122'
    sub_tag: 'A004-260618'
    tls: true
    type: 'vless'
    udp: true
    uuid: 'b2593749-691c-428c-9481-14979cba3446'
    ws-opts:
      headers:
        Host: 'xi.tbv.ccwu.cc'
        User-Agent: 'Mozilla/5.0 (Linux; Android 8.0.0; ANE-LX3 Build/HUAWEIANE-LX3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Mobile Safari/537.36'
      path: '/proxyip=us.xiabibi.cf'
    xudp: true
    packet-encoding: 'xudp'
    servername: 'xi.tbv.ccwu.cc'
  - client-fingerprint: 'chrome'
    name: '🇫🇷FR_411|633KB/s|A004-260618 01'
    network: 'ws'
    port: 443
    server: '172.64.153.88'
    sub_tag: 'A004-260618'
    tls: true
    type: 'vless'
    udp: true
    uuid: 'b2593749-691c-428c-9481-14979cba3446'
    ws-opts:
      headers:
        Host: 'xi.tbv.ccwu.cc'
        User-Agent: 'Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36'
      path: '/proxyip=us.xiabibi.cf'
    xudp: true
    packet-encoding: 'xudp'
    servername: 'xi.tbv.ccwu.cc'
  - client-fingerprint: 'chrome'
    name: '🇫🇷FR_380|1.5MB/s|M003-260806 01'
    network: 'ws'
    port: 443
    server: '66.235.200.207'
    sub_tag: 'M003-260806'
    tls: true
    type: 'vless'
    udp: true
    uuid: 'b2593749-691c-428c-9481-14979cba3446'
    ws-opts:
      headers:
        Host: 'xi.tbv.ccwu.cc'
        User-Agent: 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36'
      path: '/proxyip=us.xiabibi.cf'
    xudp: true
    packet-encoding: 'xudp'
    servername: 'xi.tbv.ccwu.cc'
  - client-fingerprint: 'chrome'
    encryption: 'none'
    name: '🇫🇷FR_419|881KB/s|S004-260618 01'
    network: 'ws'
    port: 443
    server: '31.43.179.8'
    sub_tag: 'S004-260618'
    tls: true
    type: 'vless'
    udp: true
    uuid: 'b2593749-691c-428c-9481-14979cba3446'
    ws-opts:
      headers:
        Host: 'xi.tbv.ccwu.cc'
        User-Agent: 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36'
      path: '/proxyip=us.xiabibi.cf'
    xudp: true
    packet-encoding: 'xudp'
    servername: 'xi.tbv.ccwu.cc'
  - client-fingerprint: 'chrome'
    name: '🇫🇷FR_2075|718KB/s|A004-260618 01'
    network: 'ws'
    port: 443
    server: '195.26.229.222'
    sub_tag: 'A004-260618'
    tls: true
    type: 'vless'
    udp: true
    uuid: 'b2593749-691c-428c-9481-14979cba3446'
    ws-opts:
      headers:
        Host: 'xi.tbv.ccwu.cc'
        User-Agent: 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36'
      path: '/proxyip=us.xiabibi.cf'
    xudp: true
    packet-encoding: 'xudp'
    servername: 'xi.tbv.ccwu.cc'
  - client-fingerprint: 'chrome'
    name: '🇫🇷FR_424|742KB/s|A004-260618 01'
    network: 'ws'
    port: 443
    server: '45.131.7.162'
    sub_tag: 'A004-260618'
    tls: true
    type: 'vless'
    udp: true
    uuid: 'b2593749-691c-428c-9481-14979cba3446'
    ws-opts:
      headers:
        Host: 'xi.tbv.ccwu.cc'
        User-Agent: 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36'
      path: '/proxyip=us.xiabibi.cf'
    xudp: true
    packet-encoding: 'xudp'
    servername: 'xi.tbv.ccwu.cc'
  - client-fingerprint: 'chrome'
    encryption: 'none'
    name: '🇫🇷FR_428|1.1MB/s|S004-260618 01'
    network: 'ws'
    port: 443
    server: '31.43.179.137'
    sub_tag: 'S004-260618'
    tls: true
    type: 'vless'
    udp: true
    uuid: 'b2593749-691c-428c-9481-14979cba3446'
    ws-opts:
      headers:
        Host: 'xi.tbv.ccwu.cc'
        User-Agent: 'Mozilla/5.0 (X11; U; Linux x86_64; en-US) AppleWebKit/533.2 (KHTML, like Gecko) Chrome/5.0.342.1 Safari/533.2'
      path: '/proxyip=us.xiabibi.cf'
    xudp: true
    packet-encoding: 'xudp'
    servername: 'xi.tbv.ccwu.cc'
  - client-fingerprint: 'chrome'
    name: '🇺🇸US_479|190KB/s|A001-260618 01'
    network: 'ws'
    port: 443
    server: '172.67.213.128'
    sub_tag: 'A001-260618'
    tls: true
    type: 'vless'
    udp: true
    uuid: '7e26fd8f-d75a-473d-84ba-9f4e3f47d086'
    ws-opts:
      headers:
        Host: '9-m20.cd6b506e-5a88-4c5d-9e11-906f39613c04.kdns.fr'
        User-Agent: 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36'
      path: '/8qMLgNapWf6SBxo8fhQlVPYO'
    xudp: true
    packet-encoding: 'xudp'
    servername: '9-m20.cd6b506e-5a88-4c5d-9e11-906f39613c04.kdns.fr'
    _poolOnly: true
  - cipher: 'aes-256-gcm'
    name: '🇺🇸US_620|1.6MB/s|A004-260618 01'
    password: 'pKEW8JPByTVTLtM'
    port: 4444
    server: '15.204.247.206'
    sub_tag: 'A004-260618'
    type: 'ss'
    udp: true
  - client-fingerprint: 'chrome'
    name: '🇺🇸US_451|458KB/s|F003-260618 01'
    network: 'ws'
    port: 443
    server: '172.67.214.165'
    sub_tag: 'F003-260618'
    tls: true
    type: 'vless'
    udp: true
    uuid: '7e26fd8f-d75a-473d-84ba-9f4e3f47d086'
    ws-opts:
      headers:
        Host: '5-backend-infra-m20.g000g.ccwu.cc'
        User-Agent: 'Mozilla/5.0 (Linux; Android 6.0.1; vivo 1603 Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.83 Mobile Safari/537.36'
      path: '/8qMLgNapWf6SBxo8fhQlVPYO'
    xudp: true
    packet-encoding: 'xudp'
    servername: '5-backend-infra-m20.g000g.ccwu.cc'
proxy-groups:
  - name: 'PROXY'
    type: 'select'
    proxies:
      - 'DIRECT'
      - '🇺🇸US_691|124KB/s|R002-260618 01'
      - '🇺🇸US_174|1.1MB/s|R002-260618 01'
      - '🇺🇸US_473|1.4MB/s|P002-260618 01'
      - '🇺🇸US_566|735KB/s|R002-260618 01'
      - '🇺🇸US_624|1.4MB/s 01'
      - '🇺🇸US_13|402KB/s|A004-260618 01'
      - '🇺🇸US_466|979KB/s 01'
      - '🇺🇸US_90|1.1MB/s|A004-260618 01'
      - '🇺🇸US_412|1013KB/s|A004-260618 01'
      - '🇺🇸US_28|591KB/s|T001-260618 01'
      - '🇺🇸US_119|1.5MB/s|B007-260618 01'
      - '🇺🇸US_325|1.2MB/s|R002-260618 01'
      - '🇺🇸US_70|1.3MB/s|C002-260622 01'
      - '🇺🇸US_16|892KB/s 01'
      - '🇺🇸US_471|1.0MB/s|K001-260618 01'
      - '🇺🇸US-140.82.63.79-404'
      - '🇫🇷FR_425|1.3MB/s|A004-260618 01'
      - '🇫🇷FR_340|1.2MB/s|A004-260618 01'
      - '🇺🇸US_424|1.9MB/s 01'
      - '🇺🇸US_821|1.2MB/s|M002-260618 01'
      - '🇺🇸US_748|892KB/s|A004-260618 01'
      - '🇺🇸US_799|1.5MB/s|A004-260618 01'
      - '🇫🇷FR_381|1.0MB/s|S004-260618 01'
      - '美国+CloudFlare节点-3467fe599d055525'
      - '🇫🇷FR_359|767KB/s|A004-260618 01'
      - '🇫🇷FR_271|1.4MB/s|S001-260618 01'
      - '🇫🇷FR_414|1.0MB/s|A004-260618 01'
      - '🇫🇷FR_421|1.4MB/s|A004-260618 01'
      - '🇫🇷FR_423|799KB/s|A004-260618 01'
      - '🇫🇷FR_351|1.4MB/s|A004-260618 01'
      - '🇫🇷FR_273|569KB/s|S001-260618 01'
      - '🇫🇷FR_361|567KB/s|A004-260618 01'
      - '🇫🇷FR_420|1.2MB/s|A004-260618 01'
      - '🇫🇷FR_358|1.6MB/s|A004-260618 01'
      - '🇫🇷FR_411|633KB/s|A004-260618 01'
      - '🇫🇷FR_380|1.5MB/s|M003-260806 01'
      - '🇫🇷FR_419|881KB/s|S004-260618 01'
      - '🇫🇷FR_2075|718KB/s|A004-260618 01'
      - '🇫🇷FR_424|742KB/s|A004-260618 01'
      - '🇫🇷FR_428|1.1MB/s|S004-260618 01'
      - '🇺🇸US_479|190KB/s|A001-260618 01'
      - '🇺🇸US_620|1.6MB/s|A004-260618 01'
      - '🇺🇸US_451|458KB/s|F003-260618 01'
rules:
  - 'MATCH,PROXY'
